<a href="https://colab.research.google.com/github/ArpitSahu2/ml.session2/blob/main/b2_gla_session2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello gla batch 2")


hello gla batch 2


In [ ]:
print("set for session 2")

set for session 2


In [ ]:
s="Arpit"
a=19
m=79.5
b=True
l=[s,a,m,b]
print(l)

['Arpit', 19, 79.5, True]


In [ ]:
s = ["Math", "Science", "History", "English", "Computer Science"]
print(s[0])
print(s[-1])s = ["Math", "Science", "History", "English", "Computer Science"]
print(s[0])
print(s[-1])


In [ ]:
students = {
    "arpit": {"marks": 85, "attendance": 80, "study_hours": 2},
    "ani": {"marks": 65, "attendance": 60, "study_hours": 5},
    "ashutosh": {"marks": 40, "attendance": 90, "study_hours": 0},
    "samridh": {"marks": 15, "attendance": 70, "study_hours": 3},
    "somya": {"marks": 75, "attendance": 76, "study_hours": 1}
}


for name, data in students.items():
    marks = data["marks"]
    attendance = data["attendance"]
    study_hours = data["study_hours"]

    print(f"\n{name}'s Report:")


    if marks > 75:
        print("Performance: Strong")
    elif marks >= 40:
        print("Performance: Needs Improvement")
    elif marks < 20:
        print("Performance: Fail - Repeat Class")


    if attendance < 75:
        print("Warning: Low Attendance")


    if study_hours < 1:
        print("Warning: Needs More Study Time")



arpit's Report:
Performance: Strong

ani's Report:
Performance: Needs Improvement

ashutosh's Report:
Performance: Needs Improvement

samridh's Report:
Performance: Fail - Repeat Class

somya's Report:
Performance: Needs Improvement


In [ ]:
transactions = [
    {"transaction_id": "TX101", "amount": 6200, "method": "Credit Card"},
    {"transaction_id": "TX102", "amount": 5500, "method": "Gift Card"},
    {"transaction_id": "TX103", "amount": 1200, "method": "Gift Card"},
    {"transaction_id": "TX104", "amount": 8000, "method": "Gift Card"},
    {"transaction_id": "TX105", "amount": 450, "method": "PayPal"}
]

f = []

for i in transactions:
    if i["amount"] > 5000 and i["method"] == "Gift Card":
        f.append(i["transaction_id"])

print(f)

In [ ]:
def result(marks):
  if marks>=27:
    return "Pass"
  else:
    return "Fail"
marks = int(input())
print(result(marks))


In [ ]:
# #numpy array
# numerical data focused
# usually holds one meain numeric type
# mathemathical operation
# opreation can apply to whole array

In [ ]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
print(arr.shape)

matrix=np.array([[10, 20 ,30],[40, 50 ,60]])
print(matrix)
print(matrix.shape)


[10 20 30 40]
(4,)
[[10 20 30]
 [40 50 60]]
(2, 3)


In [ ]:
marks= np.array([78, 91, 55, 72, 40, 88, 98, 81, 11, 23, 78, 88, 91, 96])
avg = np.mean(marks)
highest = np.max(marks)
lowest = np.min(marks)
c = np.sum(marks> 75)
print(avg)
print( highest)
print( lowest)
print(c)


70.71428571428571
98
11
9


In [ ]:
from google.colab import files
uploaded=files.upload()

Saving session4_dummy_students_data.csv to session4_dummy_students_data.csv


In [ ]:
import pandas as pd

df = pd.read_csv("session4_dummy_students_data.csv")

df.head()




,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82
1,102,Diya,16,Delhi,91,88,94,96,11,10,93
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60
3,104,Meera,16,Noida,72,79,81,89,7,8,78
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45


In [ ]:
math_scores=df["math"].to_numpy()
print(math_scores)
print(type(math_scores))
print(math_scores.mean())

[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
<class 'numpy.ndarray'>
69.5


In [ ]:
import pandas as pd
import numpy as np



def get_result(avg) :
  if avg>=40:
    return "Pass"
  return "fail"

df = pd.read_csv("session4_dummy_students_data.csv")


df["average"]=df[["math","science","english"]].mean(axis=1)
df["result"]=df["average"].apply(get_result)

print("fill data")
print(df)

fill data
    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  M

In [ ]:
#Student perfformace analyser
Read session4_dummy_students.csv
create an average column using math,science and english.
create a result column:Pass if average >=40,otherwise fail.
print class average
print highest average and lowest average subject wise.
print top