<a href="https://colab.research.google.com/github/ArpitSahu2/ml.BootCamp2026/blob/main/b2_session4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#first code snippet
marks=[78,63,62]
avg=sum(marks)/ len(marks)
print(avg)

67.66666666666667


In [2]:
#second code snipptt
def caclculate_average(marks):
  return sum(marks)/ len(marks)
marks=[78,63,62]
print(caclculate_average(marks))

67.66666666666667


In [3]:
def get_result_status(score):
    if score >= 27:
        return "Pass"
    return "Fail"

print(get_result_status(85))
print(get_result_status(32))

Pass
Pass


In [4]:
import numpy as np

arr=np.array([10,20,30,40])
print(arr)
print(arr.shape)


matrix =np.array([
    [10,20,30],
    [40,50,60]
])
print(matrix)
print(matrix.shape)

[10 20 30 40]
(4,)
[[10 20 30]
 [40 50 60]]
(2, 3)


In [5]:
#slicing?
grid = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
    [51, 52, 53, 54, 55]
])
print(grid[0,0])
print(grid[0])
print(grid[:,0])
print(grid[0:3, 0:3])
print(grid[1:4, 1:4])

11
[11 12 13 14 15]
[11 21 31 41 51]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[22 23 24]
 [32 33 34]
 [42 43 44]]


In [6]:
marks = np.array([78, 91, 55, 72, 40, 88])

print(marks > 70)

high_scores = marks[marks > 70]
print(high_scores)


[ True  True False  True False  True]
[78 91 72 88]


In [7]:
marks = np.array([78, 91, 55, 72, 40, 88])

print(marks.mean())
print(marks.min())
print(marks.max())
print(marks.sum())

70.66666666666667
40
91
424
